<div class="mysr-form"
     style="margin-top: 16px;"
     moyasar-data-amount="<?php echo $amount; ?>"
     moyasar-data-currency="<?php echo $currency; ?>"
     moyasar-data-country="<?php echo $country; ?>"
     moyasar-data-description="<?php echo $description; ?>"
     moyasar-data-api-key="<?php echo $apiKey; ?>"
     moyasar-data-networks="<?php echo implode(',', $networks); ?>"
     moyasar-data-methods="<?php echo implode(',', $methods); ?>"
     moyasar-data-site-url="<?php echo $site_url; ?>"
     moyasar-data-callback-url="<?php echo $callback_url; ?>"
     moyasar-data-applepay-url="<?php echo $validation_url; ?>"
     moyasar-data-applepay-label="<?php echo $applepay_label; ?>"
     moyasar-data-api-url="<?php echo $api_base_url; ?>"
     moyasar-data-checkout-nonce="<?php echo $checkout_nonce; ?>"
     moyasar-data-fixed-width="<?php echo $fixed_width; ?>"
></div>
